import { Request, Response } from "express";
import { arqueo, initChatBoxModel } from "../models/arqueo.model";

export const getArqueo = async (req: Request, res: Response): Promise<void> => {
  const page = parseInt(req.query.page as string) || 1;
  const pageSize = parseInt(req.query.pageSize as string) || 1;
  const offset = (page - 1) * pageSize;
  const zona = req.query.zona as string;

  console.log('first', zona)

  if (zona === undefined) {
    res.status(400).json("Zona no válida");
    return;
  }

  const empresa = zona === "Multired" ? "Multired" : "Servired";
  console.log("first", empresa);
  initChatBoxModel(empresa);

  try {
    const { count, rows } = await arqueo.findAndCountAll({
      attributes: [
        "supervisor",
        "id",
        "ip",
        "nombres",
        "documento",
        "sucursal",
        "puntodeventa",
        "ventabruta",
        "baseefectivo",
        "cartera",
        "totalingreso",
        "chancesabonados",
        "chancespreimpresos",
        "premiospagados",
        "efectivocajafuerte",
        "tirillarecaudo",
        "totalegresos",
        "totalbilletes",
        "totalmonedas",
        "totalarqueo",
        "sobrantefaltante",
        "totalbilletescaja",
        "totalmonedascaja",
        "totalpremioscaja",
        "total",
        "rollos_bnet",
        "rollos_fisicos",
        "diferencia",
        "nombre_juego",
        "cantidad_bnet",
        "cantidad_fisicos",
        "cantidad_faltante",
        "cantidad_tiquete",
        "descargado",
        "nombre_juego2",
        "cantidad_bnet2",
        "cantidad_fisicos2",
        "cantidad_faltante2",
        "cantidad_tiquete2",
        "descargado2",
        "nombre_juego3",
        "cantidad_bnet3",
        "cantidad_fisicos3",
        "cantidad_faltante3",
        "cantidad_tiquete3",
        "descargado3",
        "nombre_juego4",
        "cantidad_bnet4",
        "cantidad_fisicos4",
        "cantidad_faltante4",
        "cantidad_tiquete4",
        "descargado4",
        "nombre_juego5",
        "cantidad_bnet5",
        "cantidad_fisicos5",
        "cantidad_faltante5",
        "cantidad_tiquete5",
        "descargado5",
        "nombre_juego6",
        "cantidad_bnet6",
        "cantidad_fisicos6",
        "cantidad_faltante6",
        "cantidad_tiquete6",
        "descargado6",
        "nombre_juego7",
        "cantidad_bnet7",
        "cantidad_fisicos7",
        "cantidad_faltante7",
        "cantidad_tiquete7",
        "descargado7",
        "totaldescargados",
        "totalvalor",
        "requisito1",
        "observacion1",
        "requisito2",
        "observacion2",
        "requisito3",
        "observacion3",
        "requisito4",
        "observacion4",
        "requisito5",
        "observacion5",
        "requisito6",
        "observacion6",
        "requisito7",
        "observacion7",
        "requisito8",
        "observacion8",
        "requisito9",
        "observacion9",
        "requisito10",
        "observacion10",
        "requisito11",
        "observacion11",
        "requisito12",
        "observacion12",
        "requisito13",
        "observacion13",
        "requisito14",
        "observacion14",
        "requisito15",
        "observacion15",
        "requisito16",
        "observacion16",
        "requisito17",
        "observacion17",
        "requisito18",
        "observacion18",
        "requisito19",
        "observacion19",
        "requisito20",
        "observacion20",
        "requisito21",
        "observacion21",
        "requisito22",
        "observacion22",
        "requisito23",
        "observacion23",
        "requisito24",
        "observacion24",
        "requisito25",
        "observacion25",
        "requisito26",
        "observacion26",
        "requisito27",
        "observacion27",
        "requisito28",
        "observacion28",
        "requisito29",
        "observacion29",
        "requisito30",
        "observacion30",
        "requisito31",
        "observacion31",
        "requisito32",
        "observacion32",
        "requisito33",
        "observacion33",
        "requisito34",
        "observacion34",
        "requisito35",
        "observacion35",
        "nombre_observacion",
        "fechavisita",
        "horavisita",
        "latitud",
        "longitud",
      ],
      limit: pageSize,
      offset: offset,
      order: [["fechavisita", "DESC"]],
    });
    res.status(200).json({ count, datos: rows, page, pageSize });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Internal Server Error" });
  }
};

export const getArqueos = async (
  req: Request,
  res: Response
): Promise<void> => {
  const data = req.params;
  const { zona, id } = data;

  if (zona === undefined) {
    res.status(400).json("Zona no válida");
    return;
  }

  const empresa = zona === "Multired" ? "Multired" : "Servired";
  initChatBoxModel(empresa);

  try {
    const Chat = await arqueo.findAll({
      attributes: [
        "supervisor",
        "id",
        "ip",
        "nombres",
        "documento",
        "sucursal",
        "puntodeventa",
        "ventabruta",
        "baseefectivo",
        "cartera",
        "totalingreso",
        "chancesabonados",
        "chancespreimpresos",
        "premiospagados",
        "efectivocajafuerte",
        "tirillarecaudo",
        "totalegresos",
        "totalbilletes",
        "totalmonedas",
        "totalarqueo",
        "sobrantefaltante",
        "totalbilletescaja",
        "totalmonedascaja",
        "totalpremioscaja",
        "total",
        "rollos_bnet",
        "rollos_fisicos",
        "diferencia",
        "nombre_juego",
        "cantidad_bnet",
        "cantidad_fisicos",
        "cantidad_faltante",
        "cantidad_tiquete",
        "descargado",
        "nombre_juego2",
        "cantidad_bnet2",
        "cantidad_fisicos2",
        "cantidad_faltante2",
        "cantidad_tiquete2",
        "descargado2",
        "nombre_juego3",
        "cantidad_bnet3",
        "cantidad_fisicos3",
        "cantidad_faltante3",
        "cantidad_tiquete3",
        "descargado3",
        "nombre_juego4",
        "cantidad_bnet4",
        "cantidad_fisicos4",
        "cantidad_faltante4",
        "cantidad_tiquete4",
        "descargado4",
        "nombre_juego5",
        "cantidad_bnet5",
        "cantidad_fisicos5",
        "cantidad_faltante5",
        "cantidad_tiquete5",
        "descargado5",
        "nombre_juego6",
        "cantidad_bnet6",
        "cantidad_fisicos6",
        "cantidad_faltante6",
        "cantidad_tiquete6",
        "descargado6",
        "nombre_juego7",
        "cantidad_bnet7",
        "cantidad_fisicos7",
        "cantidad_faltante7",
        "cantidad_tiquete7",
        "descargado7",
        "totaldescargados",
        "totalvalor",
        "requisito1",
        "observacion1",
        "requisito2",
        "observacion2",
        "requisito3",
        "observacion3",
        "requisito4",
        "observacion4",
        "requisito5",
        "observacion5",
        "requisito6",
        "observacion6",
        "requisito7",
        "observacion7",
        "requisito8",
        "observacion8",
        "requisito9",
        "observacion9",
        "requisito10",
        "observacion10",
        "requisito11",
        "observacion11",
        "requisito12",
        "observacion12",
        "requisito13",
        "observacion13",
        "requisito14",
        "observacion14",
        "requisito15",
        "observacion15",
        "requisito16",
        "observacion16",
        "requisito17",
        "observacion17",
        "requisito18",
        "observacion18",
        "requisito19",
        "observacion19",
        "requisito20",
        "observacion20",
        "requisito21",
        "observacion21",
        "requisito22",
        "observacion22",
        "requisito23",
        "observacion23",
        "requisito24",
        "observacion24",
        "requisito25",
        "observacion25",
        "requisito26",
        "observacion26",
        "requisito27",
        "observacion27",
        "requisito28",
        "observacion28",
        "requisito29",
        "observacion29",
        "requisito30",
        "observacion30",
        "requisito31",
        "observacion31",
        "requisito32",
        "observacion32",
        "requisito33",
        "observacion33",
        "requisito34",
        "observacion34",
        "requisito35",
        "observacion35",
        "imagen_observacion",
        "nombre_observacion",
        "firma_auditoria",
        "firma_colocadora",
        "fechavisita",
        "horavisita",
        "latitud",
        "longitud",
      ],
      where: {
        id: id,
      },
      order: [["fechavisita", "DESC"]],
    });
    res.status(200).json(Chat);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Internal Server Error" });
  }
};
